### ISSUE TITLE
Failing to acquire database when update=?True

### ISSUE THREAD

**Issue by nickolas1969** [coolbho3k/manuf#19]
Just in the last few days I noticed my scripts using manuf.py started failing to get the manuf database from gitlab.

I'm not sure what changed, but I tried installing it on my vdi clean and it is reproducible.

I am able to see the database in the manuf_url from the module using chrome on the same system. 

Nick

```
$ python3
Python 3.6.8 (default, Feb 14 2019, 22:09:48)
[GCC 7.4.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from manuf import manuf
>>> p = manuf.MacParser(update=True)
Traceback (most recent call last):
  File "/home/nicko/manuf/manuf/manuf.py", line 142, in update
    response = urlopen(manuf_url)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nicko/manuf/manuf/manuf.py", line 68, in __init__
    self.update()
  File "/home/nicko/manuf/manuf/manuf.py", line 144, in update
    raise URLError("Failed downloading OUI database")
urllib.error.URLError: <urlopen error Failed downloading OUI database>
>>>
```

**Comment by ComputeAllTheThings** [comment]
I stumbled across that too, the server is blocking Python User-Agents.  This stackoverflow discusses some possible solutions: https://stackoverflow.com/questions/24226781/changing-user-agent-in-python-3-for-urrlib-request-urlopen
