### ISSUE TITLE
Error 503

### ISSUE THREAD

**Issue by solsticedhiver** [coolbho3k/manuf#29]
```
$ manuf -u
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/manuf/manuf.py", line 164, in update
    response = urlopen(Request(wfa_url, headers={'User-Agent': 'Mozilla'}))
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/manuf", line 33, in <module>
    sys.exit(load_entry_point('manuf==1.1.1', 'console_scripts', 'manuf')())
  File "/usr/lib/python3.9/site-packages/manuf/manuf.py", line 324, in main
    parser = MacParser(manuf_name=args.manuf, update=args.update)
  File "/usr/lib/python3.9/site-packages/manuf/manuf.py", line 70, in __init__
    self.update()
  File "/usr/lib/python3.9/site-packages/manuf/manuf.py", line 166, in update
    raise URLError("Failed downloading WFA database")
urllib.error.URLError: <urlopen error Failed downloading WFA database>

```

It seems https://code.wireshark.org/review/gitweb?p=wireshark.git;a=blob_plain;f=manuf has moved to https://gitlab.com/wireshark/wireshark/raw/master/manuf

Please update the script. Thanks

**Comment by joshschmelzle** [comment]
@coolbho3k any chance we can get this merged and a new version of manuf pushed to PyPI?

**Comment by coolbho3k** [comment]
@joshschmelzle merged, I'll see about pushing to pypi soon

**Comment by joshschmelzle** [comment]
Thank you! The https://github.com/WLAN-Pi project appreciates your work.

**Comment by coolbho3k** [comment]
@joshschmelzle Done! https://pypi.org/project/manuf/1.1.3/
